version: "2"

services:
  php:
    image: php:7.1-fpm-alpine
    volumes:
      - .:/var/www

  nginx:
    image: nginx:latest
    links:
      - php
    ports:
      - '7080:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
